# Basic Python: Project <a id='intro'></a>

# Contents <a id='back'></a>

* [Introduction](#intro)
* [Stage 1. Data overview](#data_overview)
    * [1.1 Goal](#data_goal)
    * [1.2 Stages](#data_stages)
* [Stage 2. Data preprocessing](#data_preprocessing)
    * [2.1 Header style](#header_style)
    * [2.2 Missing values](#missing_values)
    * [2.3 Duplicates](#duplicates)
    * [2.4 Conclusions](#data_preprocessing_conclusions)
* [Stage 3. Testing the hypotheses](#hypotheses)
    * [3.1 Hypothesis 1: User activity in the two cities](#activity)
    * [3.2 Hypothesis 2: TV show preferences on weekdays vs. weekends](#week)
    * [3.3 Hypothesis 3: Genre preferences in Springfield and Shelbyville](#genre)
* [Findings](#end)

## Introduction <a id='intro'></a>
Whenever we are doing research, we need to formulate hypotheses that we can then test. Sometimes we accept these hypotheses; other times, we reject them. To make the right decisions, a business must be able to understand whether or not it is making the right assumptions.

In this project, you will work with data from the entertainment industry. You will study a dataset with records on movies and TV shows. The research will focus on the "Golden Age" of television, which began in 1999 with the release of *The Sopranos* and is still ongoing.

The aim of this project is to investigate how the number of votes a title receives impacts its ratings. The assumption is that highly-rated shows (we will focus on TV shows, ignoring movies) released during the "Golden Age" of television also have the most votes.


### Goal 
Test three hypotheses:
1. User activity differs depending on the day of the week and from city to city. 
2. On the weekdays (Monday through Friday, Springfield and Shelbyville residents watch similar TV show genres. On the weekends (Saturday and Sunday), the results are more varied.  
3. Springfield and Shelbyville audiences have different preferences. In Springfield, for example, they prefer reality TV shows on weekdays, while Shelbyville has more sit-com fans.


### Stages 
Data on movies and shows is stored in the `/datasets/movies_and_shows.csv` file. There is no information about the quality of the data, so you will need to explore it before doing the analysis.

First, you'll evaluate the quality of the data and see whether its issues are significant. Then, during data preprocessing, you will try to account for the most critical problems.
 
Your project will consist of three stages:
 1. Data overview
 2. Data preprocessing
 3. Data analysis

## Stage 1. Data overview <a id='data_review'></a>

Open and explore the data.

You'll need `pandas`, so import it.

In [1]:
# importing pandas
import pandas as pd

Read the `movies_and_shows.csv` file from the `datasets` folder and save it in the `df` variable:

In [2]:
# reading the files and storing them to df
df = pd.read_csv("/datasets/movies_and_shows.csv")

Print the first 10 table rows:

In [3]:
# obtaining the first 10 rows from the df table
# hint: you can use head() and tail() in Jupyter Notebook without wrapping them into print()
df.head(10)

,name,Character,r0le,TITLE,Type,release Year,genres,imdb sc0re,imdb v0tes
0,Robert De Niro,Travis Bickle,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
1,Jodie Foster,Iris Steensma,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
2,Albert Brooks,Tom,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
3,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
4,Cybill Shepherd,Betsy,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
5,Peter Boyle,Wizard,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
6,Leonard Harris,Senator Charles Palantine,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
7,Diahnne Abbott,Concession Girl,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
8,Gino Ardito,Policeman at Rally,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
9,Martin Scorsese,Passenger Watching Silhouette,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0

Obtain the general information about the table with one command:

In [4]:
# obtaining general information about the data in df
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85579 entries, 0 to 85578
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0      name       85579 non-null  object
 1   Character     85579 non-null  object
 2   r0le          85579 non-null  object
 3   TITLE         85578 non-null  object
 4     Type        85579 non-null  object
 5   release Year  85579 non-null  int64
 6   genres        85579 non-null  object
 7   imdb sc0re    80970 non-null  float64
 8   imdb v0tes    80853 non-null  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 5.9+ MB

       release Year    imdb sc0re    imdb v0tes
count  85579.000000  80970.000000  8.085300e+04
mean    2015.879994      6.425877  5.978271e+04
std        7.724668      1.122655  1.846287e+05
min     1954.000000      1.500000  5.000000e+00
25%     2015.000000      5.700000  1.266000e+03
50%     2018.000000      6.500000  5.448000e+03
75%     2021.000000      7.200000  3.360900e+04
max     2022.000000      9.500000  2.294231e+06

### Conclusions <a id='data_review_conclusions'></a> 

Each row in the table stores data about a movie or show. The columns can be divided into two categories: the first is about the roles held by different people who worked on the movie or show (role, name of the actor or director, and character if the row is about an actor); the second category is information about the movie or show itself (title, release year, genre, imdb figures).

It's clear that there is sufficient data to do the analysis and evaluate our assumption. However, to move forward, we need to preprocess the data.

The table contains nine columns. The majority store the same data type: object. The only exceptions are `'release Year'` (int64 type), `'imdb sc0re'` (float64 type) and `'imdb v0tes'` (float64 type). Scores and votes will be used in our analysis, so it's important to verify that they are present in the dataframe in the appropriate numeric format. Three columns (`'TITLE'`, `'imdb sc0re'` and `'imdb v0tes'`) have missing values.

According to the documentation:
- `'name'` — actor/director's name and last name
- `'Character'` — character played (for actors)
- `'r0le '` — the person's contribution to the title (it can be in the capacity of either actor or director)
- `'TITLE '` — title of the movie (show)
- `'  Type'` — show or movie
- `'release Year'` — year when movie (show) was released
- `'genres'` — list of genres under which the movie (show) falls
- `'imdb sc0re'` — score on IMDb
- `'imdb v0tes'` — votes on IMDb

We can see three issues with the column names:
1. Some names are uppercase, while others are lowercase.
2. There are names containing whitespace.
3. A few column names have digit '0' instead of letter 'o'.

## Stage 2. Data preprocessing <a id='data_preprocessing'></a>
Correct the formatting in the column headers and deal with the missing values. Then, check whether there are duplicates in the data.

### Header style <a id='header_style'></a>
Print the column header:

In [5]:
# the list of column names in the df table
print(df.columns)

Index(['   name', 'Character', 'r0le', 'TITLE', '  Type', 'release Year',
       'genres', 'imdb sc0re', 'imdb v0tes'],
      dtype='object')

Change the column names according to the rules of good style:
* If the name has several words, use snake_case
* All characters must be lowercase
* Remove whitespace
* Replace zero with letter 'o'

In [6]:
# renaming columns
df.rename(columns={' name': 'name', 'Character': 'character', 'r0le': 'role', 'TITLE': 'title', ' Type': 'type', 'release Year': 'release_year', 'genres': 'genre', 'imdb sc0re': 'imdb_score', 'imdb v0tes': 'imdb_votes', 'tv shows': 'tv_shows'}, inplace=True)

Check the result. Print the names of the columns once more:

In [7]:
# checking result: the list of column names

df.columns = df.columns.str.strip()

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85579 entries, 0 to 85578
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          85579 non-null  object
 1   character     85579 non-null  object
 2   role          85579 non-null  object
 3   title         85578 non-null  object
 4   Type          85579 non-null  object
 5   release_year  85579 non-null  int64
 6   genre         85579 non-null  object
 7   imdb_score    80970 non-null  float64
 8   imdb_votes    80853 non-null  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 5.9+ MB
None

In [8]:
df.rename(columns={'Type': 'type'}, inplace=True)

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85579 entries, 0 to 85578
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          85579 non-null  object
 1   character     85579 non-null  object
 2   role          85579 non-null  object
 3   title         85578 non-null  object
 4   type          85579 non-null  object
 5   release_year  85579 non-null  int64
 6   genre         85579 non-null  object
 7   imdb_score    80970 non-null  float64
 8   imdb_votes    80853 non-null  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 5.9+ MB
None

### Missing values <a id='missing_values'></a>
First, find the number of missing values in the table. To do so, combine two `pandas` methods:

In [9]:
# calculating missing values
df.isna().sum()

name               0
character          0
role               0
title              1
type               0
release_year       0
genre              0
imdb_score      4609
imdb_votes      4726
dtype: int64

We identified missing values in several columns. While the missing value in `'title'` isn't critical, missing values in `'imdb_score'` and `'imdb_votes'` affect around 6% of the data, which could impact our analysis. To ensure data integrity, we'll drop all rows with missing values.

In [10]:
# dropping rows where columns with scores, and votes have missing values

df = df.dropna(subset= ['imdb_score', 'imdb_votes'])

Make sure the table doesn't contain any more missing values. Count the missing values again.

In [11]:
# counting missing values

df.isna().sum()

name            0
character       0
role            0
title           0
type            0
release_year    0
genre           0
imdb_score      0
imdb_votes      0
dtype: int64

### Duplicates <a id='duplicates'></a>
Find the number of duplicate rows in the table using one command:

In [12]:
# counting duplicate rows

print(df.duplicated().sum())

6994

Review the duplicate rows to determine if removing them would distort our dataset.

In [13]:
# Produce table with duplicates (with original rows included) and review last 5 rows

duplicates = df[df.duplicated(keep=False)]

duplicates.tail(5)

,name,character,role,title,type,release_year,genre,imdb_score,imdb_votes
85569,Jessica Cediel,Liliana Navarro,ACTOR,Lokillo,MOVIE,2021,['comedy'],3.8,68.0
85570,Javier Gardeaz?­bal,"Agust??n ""Peluca"" Ort??z",ACTOR,Lokillo,MOVIE,2021,['comedy'],3.8,68.0
85571,Carla Giraldo,Valery Reinoso,ACTOR,Lokillo,MOVIE,2021,['comedy'],3.8,68.0
85572,Ana Mar??a S?­nchez,Lourdes,ACTOR,Lokillo,MOVIE,2021,['comedy'],3.8,68.0
85577,Isabel Gaona,Cacica,ACTOR,Lokillo,MOVIE,2021,['comedy'],3.8,68.0

There are two clear duplicates in the printed rows. We can safely remove them.
Call the `pandas` method for getting rid of duplicate rows:

In [14]:
# removing duplicate rows

df = df.drop_duplicates()

print(df.head())

              name                character   role        title   type  \
0   Robert De Niro            Travis Bickle  ACTOR  Taxi Driver  MOVIE
1     Jodie Foster            Iris Steensma  ACTOR  Taxi Driver  MOVIE
2    Albert Brooks                      Tom  ACTOR  Taxi Driver  MOVIE
3    Harvey Keitel  Matthew 'Sport' Higgins  ACTOR  Taxi Driver  MOVIE
4  Cybill Shepherd                    Betsy  ACTOR  Taxi Driver  MOVIE

   release_year               genre  imdb_score  imdb_votes
0          1976  ['drama', 'crime']         8.2    808582.0
1          1976  ['drama', 'crime']         8.2    808582.0
2          1976  ['drama', 'crime']         8.2    808582.0
3          1976  ['drama', 'crime']         8.2    808582.0
4          1976  ['drama', 'crime']         8.2    808582.0

Check for duplicate rows once more to make sure you have removed all of them:

In [15]:
# checking for duplicates

print(df.duplicated().sum())

0

Now get rid of implicit duplicates in the `'type'` column. For example, the string `'SHOW'` can be written in different ways. These kinds of errors will also affect the result.

Print a list of unique `'type'` names, sorted in alphabetical order. To do so:
* Retrieve the intended dataframe column 
* Apply a sorting method to it
* For the sorted column, call the method that will return all unique column values

In [16]:
# viewing unique type names

print(df['type'].unique())

['MOVIE' 'the movie' 'tv show' 'shows' 'movies' 'tv shows' 'tv series'
 'tv' 'SHOW']

In [17]:
# add sorting for the sorted column

df['type'].sort_values().unique()

array(['MOVIE', 'SHOW', 'movies', 'shows', 'the movie', 'tv', 'tv series',
       'tv show', 'tv shows'], dtype=object)

Look through the list to find implicit duplicates of `'show'` (`'movie'` duplicates will be ignored since the assumption is about shows). These could be names written incorrectly or alternative names of the same genre.

You will see the following implicit duplicates:
* `'shows'`
* `'SHOW'`
* `'tv show'`
* `'tv shows'`
* `'tv series'`
* `'tv'`

To get rid of them, declare the function `replace_wrong_show()` with two parameters: 
* `wrong_shows_list=` — the list of duplicates
* `correct_show=` — the string with the correct value

The function should correct the names in the `'type'` column from the `df` table (i.e., replace each value from the `wrong_shows_list` list with the value in `correct_show`).

In [18]:
# function for replacing implicit duplicates

def replace_wrong_show(df, replace_wrong_shows_list, correct_show):
    df['type'] = df['type'].replace(replace_wrong_shows_list, correct_show)

In [19]:
replace_wrong_shows_list = ['shows', 'SHOW', 'tv show', 'tv shows', 'tv series', 'tv']
correct_show = 'show'

Call `replace_wrong_show()` and pass it arguments so that it clears implicit duplicates and replaces them with `SHOW`:

In [20]:
replace_wrong_show(df, replace_wrong_shows_list, correct_show)

In [21]:
# removing implicit duplicates

df['type'].value_counts()

MOVIE        60173
show         13604
the movie       44
movies          38
Name: type, dtype: int64

Make sure the duplicate names are removed. Print the list of unique values from the `'type'` column:

In [22]:
# viewing unique genre names

print(df['type'].unique())

['MOVIE' 'the movie' 'show' 'movies']

### Conclusions <a id='data_preprocessing_conclusions'></a>
We detected three issues with the data:

- Incorrect header styles
- Missing values
- Duplicate rows and implicit duplicates

The headers have been cleaned up to make processing the table simpler.

All rows with missing values have been removed. 

The absence of duplicates will make the results more precise and easier to understand.

Now we can move on to our analysis of the prepared data.

## Stage 3. Data analysis <a id='hypotheses'></a>

Based on the previous project stages, you can now define how the assumption will be checked. Calculate the average amount of votes for each score (this data is available in the `imdb_score` and `imdb_votes` columns), and then check how these averages relate to each other. If the averages for shows with the highest scores are bigger than those for shows with lower scores, the assumption appears to be true.

Based on this, complete the following steps:

- Filter the dataframe to only include shows released in 1999 or later.
- Group scores into buckets by rounding the values of the appropriate column (a set of 1-10 integers will help us make the outcome of our calculations more evident without damaging the quality of our research).
- Identify outliers among scores based on their number of votes, and exclude scores with few votes.
- Calculate the average votes for each score and check whether the assumption matches the results.

To filter the dataframe and only include shows released in 1999 or later, you will take two steps. First, keep only titles published in 1999 or later in our dataframe. Then, filter the table to only contain shows (movies will be removed).

In [23]:
# using conditional indexing modify df so it has only titles released after 1999 (with 1999 included)

df_1999_onwards = df[df['release_year'] >= 1999]


# give the slice of dataframe new name

df_1999_onwards

,name,character,role,title,type,release_year,genre,imdb_score,imdb_votes
1664,Jeff Probst,Himself - Host,ACTOR,Survivor,show,2000,['reality'],7.4,24687.0
1955,Benicio del Toro,Franky Four Fingers,ACTOR,Snatch,MOVIE,2000,"['crime', 'comedy']",8.3,841435.0
1956,Dennis Farina,Cousin Avi,ACTOR,Snatch,MOVIE,2000,"['crime', 'comedy']",8.3,841435.0
1957,Vinnie Jones,Bullet Tooth Tony,ACTOR,Snatch,MOVIE,2000,"['crime', 'comedy']",8.3,841435.0
1958,Brad Pitt,Mickey O'Neil,ACTOR,Snatch,MOVIE,2000,"['crime', 'comedy']",8.3,841435.0
...,...,...,...,...,...,...,...,...,...
85573,A??da Morales,Maritza,ACTOR,Lokillo,the movie,2021,['comedy'],3.8,68.0
85574,Adelaida Buscato,Mar??a Paz,ACTOR,Lokillo,the movie,2021,['comedy'],3.8,68.0
85575,Luz Stella Luengas,Karen Bayona,ACTOR,Lokillo,the movie,2021,['comedy'],3.8,68.0
85576,In??s Prieto,Fanny,ACTOR,Lokillo,the movie,2021,['comedy'],3.8,68.0
85578,Julian Gaviria,unknown,DIRECTOR,Lokillo,the movie,2021,['comedy'],3.8,68.0

In [24]:
# repeat conditional indexing so df has only shows (movies are removed as result)

df_shows_only = df_1999_onwards[df_1999_onwards['type'].str.strip() == 'show']

The scores that are to be grouped should be rounded. For instance, titles with scores like 7.8, 8.1, and 8.3 will all be placed in the same bucket with a score of 8.

In [25]:
# ensuring that the column name `imbd_score` exists in the dataframe

print(df_shows_only.columns)


# previewing the dataframe

print(df_shows_only.head())

Index(['name', 'character', 'role', 'title', 'type', 'release_year', 'genre',
       'imdb_score', 'imdb_votes'],
      dtype='object')
                  name                character   role      title  type  \
1664       Jeff Probst           Himself - Host  ACTOR   Survivor  show
2076     Mayumi Tanaka  Monkey D. Luffy (voice)  ACTOR  One Piece  show
2077      Kazuya Nakai     Roronoa Zoro (voice)  ACTOR  One Piece  show
2078     Akemi Okamura             Nami (voice)  ACTOR  One Piece  show
2079  Kappei Yamaguchi            Usopp (voice)  ACTOR  One Piece  show

      release_year                                              genre  \
1664          2000                                        ['reality']
2076          1999  ['animation', 'action', 'comedy', 'drama', 'fa...
2077          1999  ['animation', 'action', 'comedy', 'drama', 'fa...
2078          1999  ['animation', 'action', 'comedy', 'drama', 'fa...
2079          1999  ['animation', 'action', 'comedy', 'drama', 'fa...

      imdb_score  imdb_votes
1664         7.4     24687.0
2076         8.8    117129.0
2077         8.8    117129.0
2078         8.8    117129.0
2079         8.8    117129.0

In [26]:
# rounding column with scores

df_shows_only['imdb_score'] = df_shows_only['imdb_score'].round()


# checking the outcome with tail()

print(df_shows_only.tail())

                      name character      role      title  type  release_year  \
85433     Maneerat Kam-Uan        Ae     ACTOR  Let's Eat  show          2021
85434    Rudklao Amratisha   unknown     ACTOR  Let's Eat  show          2021
85435      Jaturong Mokjok   unknown     ACTOR  Let's Eat  show          2021
85436     Pisamai Wilaisak   unknown     ACTOR  Let's Eat  show          2021
85437  Sarawut Wichiensarn   unknown  DIRECTOR  Let's Eat  show          2021

                     genre  imdb_score  imdb_votes
85433  ['drama', 'comedy']         8.0         5.0
85434  ['drama', 'comedy']         8.0         5.0
85435  ['drama', 'comedy']         8.0         5.0
85436  ['drama', 'comedy']         8.0         5.0
85437  ['drama', 'comedy']         8.0         5.0

/tmp/ipykernel_124/3444705663.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_shows_only['imdb_score'] = df_shows_only['imdb_score'].round()

It is now time to identify outliers based on the number of votes.

In [27]:
# Use groupby() for scores and count all unique values in each group, print the result

print(df_shows_only.tail())

                      name character      role      title  type  release_year  \
85433     Maneerat Kam-Uan        Ae     ACTOR  Let's Eat  show          2021
85434    Rudklao Amratisha   unknown     ACTOR  Let's Eat  show          2021
85435      Jaturong Mokjok   unknown     ACTOR  Let's Eat  show          2021
85436     Pisamai Wilaisak   unknown     ACTOR  Let's Eat  show          2021
85437  Sarawut Wichiensarn   unknown  DIRECTOR  Let's Eat  show          2021

                     genre  imdb_score  imdb_votes
85433  ['drama', 'comedy']         8.0         5.0
85434  ['drama', 'comedy']         8.0         5.0
85435  ['drama', 'comedy']         8.0         5.0
85436  ['drama', 'comedy']         8.0         5.0
85437  ['drama', 'comedy']         8.0         5.0

In [28]:
# use groupby() and count() methods for the 'imdb_score' column

grouped_data = df_shows_only.groupby('imdb_score')['imdb_score'].count()

print(grouped_data)

imdb_score
2.0       24
3.0       27
4.0      180
5.0      592
6.0     2494
7.0     4706
8.0     4842
9.0      557
10.0       8
Name: imdb_score, dtype: int64

Based on the aggregation performed, it is evident that scores 2 (24 voted shows), 3 (27 voted shows), and 10 (only 8 voted shows) are outliers. There isn't enough data for these scores for the average number of votes to be meaningful.

To obtain the mean numbers of votes for the selected scores (we identified a range of 4-9 as acceptable), use conditional filtering and grouping.

In [29]:
# filter dataframe using two conditions (scores to be in the range 4-9)

filtered_df_shows_only = df_shows_only[(df_shows_only['imdb_score'] >= 4) & (df_shows_only['imdb_score'] <= 9)]

# group scores and corresponding average number of votes, reset index and print the result

grouped = filtered_df_shows_only.groupby('imdb_score')['imdb_votes'].agg('mean').reset_index()
grouped

   imdb_score     imdb_votes
0         4.0    5277.583333
1         5.0    3143.942568
2         6.0    3481.717322
3         7.0    8727.068211
4         8.0   30299.460967
5         9.0  126904.109515

Now for the final step! Round the column with the averages, rename both columns, and print the dataframe in descending order.

In [30]:
# round column with averages

grouped['imdb_votes'] = grouped['imdb_votes'].round()


# rename columns

grouped = grouped.rename(columns={'imdb_score': 'scores', 'imdb_votes': 'votes'})


# print dataframe in descending order

grouped = grouped.sort_values(by='votes', ascending=False)
   

print(grouped)

   scores     votes
5     9.0  126904.0
4     8.0   30299.0
3     7.0    8727.0
0     4.0    5278.0
2     6.0    3482.0
1     5.0    3144.0

The assumption macthes the analysis: the shows with the top 3 scores have the most amounts of votes.

## Conclusion <a id='hypotheses'></a>

The research done confirms that highly-rated shows released during the "Golden Age" of television also have the most votes. While shows with score 4 have more votes than ones with scores 5 and 6, the top three (scores 7-9) have the largest number. The data studied represents around 94% of the original set, so we can be confident in our findings.